#!/usr/bin/perl

# Debian deps: libemail-mime libhtml-strip-perl
use strict;
use warnings;
use Email::Texter;
use open ':locale';

# Slurp email from stdin
my $source = do { local $/; <STDIN> };
my $email = Email::MIME->new($source);

email_texter($email);
my @text_parts = grep { defined $_->content_type and $_->content_type =~ m:^text/plain;?: } $email->parts;
print $text_parts[0]->body_str if @text_parts;
