#!/usr/bin/perl

# Email::Texter - extract essentials from verbose emails
# Copyright (C) 2014 Bearstech
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This is a simple program which invokes Email::Texter. Feed it an email to its
# stdin and it will show you the source of the texterized email.

use strict;
use warnings;
use File::Slurp;
use Email::Texter;

my $in = read_file(\*STDIN);
my $email = Email::MIME->new($in);
email_texter($email);
print $email->as_string;
